services:
  - type: web
    name: flask-demo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PORT
        value: "10000"
